# Generated by Django 3.2.9 on 2022-01-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211102_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
